// <auto-generated />
using System;
using Alchemist.Product.Data.Postgresql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alchemist.Product.Data.Postgresql.Migrations
{
    [DbContext(typeof(AlchemyContextPostgres))]
    partial class AlchemyContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alchemist.Product.Data.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("comment");

                    b.Property<short?>("CountryId")
                        .HasColumnType("smallint")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("brand_pk");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Transcript")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transcript");

                    b.HasKey("Id")
                        .HasName("component_pk");

                    b.ToTable("component", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ComponentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_group_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("component_group_pk");

                    b.ToTable("component_group", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.Country", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Transcript")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transcript");

                    b.HasKey("Id")
                        .HasName("country_pk");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.Currency", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<short?>("Code")
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("currency_pkey");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_time");

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Articul")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("articul");

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("InitShopId")
                        .HasColumnType("integer")
                        .HasColumnName("init_shop_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<short>("ProductTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Transcript")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transcript");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("product_pk");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ProductComponent", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer")
                        .HasColumnName("component_id");

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<short>("SequalNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("sequal_number");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("ProductId", "ComponentId")
                        .HasName("product_component_pk");

                    b.ToTable("product_component", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ProductPurpose", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<short>("PurposeTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose_type_id");

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("ProductId", "PurposeTypeId")
                        .HasName("product_purpose_pkey");

                    b.ToTable("product_purpose", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ProductType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product_type");

                    b.ToTable("product_type", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.PurposeComponentGroup", b =>
                {
                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Comment")
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("comment");

                    b.Property<short>("ComponentGroupId")
                        .HasColumnType("smallint")
                        .HasColumnName("component_group_id");

                    b.Property<short>("PurposeTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose_type_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.ToTable("purpose_component_group", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.PurposeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("purpose_type_pk");

                    b.ToTable("purpose_type", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caption");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("shop_pk");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ShopCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("shop_category_pk");

                    b.HasIndex("ShopId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("shop_category_itemid_unique");

                    b.ToTable("shop_category", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ShopProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("api_url");

                    b.Property<bool?>("IsActual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actual");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemUrl")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("character varying(1023)")
                        .HasColumnName("item_url");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("shop_product_pk");

                    b.HasIndex("ShopId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("shop_product_item_unique");

                    b.HasIndex("ShopId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("shop_product_unique");

                    b.ToTable("shop_product", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ShopProductCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<int>("ShopCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_category_id");

                    b.Property<long>("ShopProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("shop_product_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("shop_product_category_pk");

                    b.HasIndex("ShopProductId", "ShopCategoryId")
                        .IsUnique()
                        .HasDatabaseName("shop_product_category_unique");

                    b.ToTable("shop_product_category", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ShopProductPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<long>("ShopProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("shop_product_id");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("shop_product_price_pkey");

                    b.ToTable("shop_product_price", (string)null);
                });

            modelBuilder.Entity("Alchemist.Product.Data.ShopSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("added_ts");

                    b.Property<bool?>("IsActual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actual");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentSettingsId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_settings_id");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer")
                        .HasColumnName("shop_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedTs")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_ts");

                    b.HasKey("Id")
                        .HasName("shop_settings_pk");

                    b.ToTable("shop_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
