<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DependencyInjection.AssemblyExtensions" Version="1.0.0.5" />
    <PackageReference Include="CustomJsonConfigurationProvider" Version="1.0.0.2" />
    <PackageReference Include="Http.DelegatingRequestSender" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.5" />
    <PackageReference Include="Serilog.ContextFileSink" Version="1.0.0.1" />
    <PackageReference Include="Json.FileExtensions" Version="1.0.0" />
    <PackageReference Include="Http.RequestHandling.PerfomanceCounter" Version="1.0.0.1" />
    <PackageReference Include="WebLoader.Interfaces" Version="1.0.1.5" />
	<PackageReference Include="Message.Interfaces" Version="1.0.0.3" />
	<PackageReference Include="Message.RabbitMQ.DependencyInjection" Version="1.0.0.8" />
	<PackageReference Include="Import.Factory.Logging" Version="1.0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.BackgroundTaskQueueService\BackgroundTaskQueueService.csproj" />
    <ProjectReference Include="..\Alchemist.BrowserService.Client\Alchemist.BrowserService.Client.csproj" />
    <ProjectReference Include="..\Alchemist.DependencyInjection.Common\Alchemist.DependencyInjection.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Adapter\Alchemist.Import.Settings.DataAdapter.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.JsonAdapter\Alchemist.Import.Settings.JsonAdapter.csproj" />
    <ProjectReference Include="..\Alchemist.Log.Extensions\Alchemist.Log.Extensions.csproj" />
    <ProjectReference Include="..\Alchemist.Product.BeautyAndHealth.ImportItemHandler\Alchemist.Product.BeautyAndHealth.ImportItemHandler.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Category.ImportItemHandler\Alchemist.Product.Category.ImportItemHandler.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Import.Background\Alchemist.Product.Import.Background.csproj" />
    <ProjectReference Include="..\Shop.API.Client\Shop.API.Client.csproj" />
    <ProjectReference Include="..\Alchemist.Settings.RestAPIClient\Alchemist.Settings.RestAPIClient.csproj" />
    <ProjectReference Include="..\ShopImport.Service.Infrastructure.Module\ShopImport.Service.Infrastructure.Module.csproj" />
    <ProjectReference Include="..\ShopImport.Service.Infrastructure\ShopImport.Service.Category.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="ImportSettings\Ozon.categories.requestheaders.Firefox.Standart.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>  

  <!--<Target Name="CopyDIDir" AfterTargets="Build">
    <ItemGroup>
      <DIFiles Include="$(PkgDependencyInjection_AssemblyExtensions)\dependencies\*.dll"></DIFiles>
    </ItemGroup>
    <Copy SourceFiles="@(DIFiles)" DestinationFolder="$(OutDir)"></Copy>
  </Target>-->

</Project>
