<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>    
    <PackageReference Include="Message.SignalR.HubMessage.DependencyInjection" Version="1.0.0.4" />
    <PackageReference Include="Message.Interfaces" Version="1.0.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="Json.FileExtensions" Version="1.0.0" />
	<PackageReference Include="Import.Factory.Interfaces" Version="1.0.0.2" />
	<PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Common\Alchemist.Common.csproj" />
    <ProjectReference Include="..\Alchemist.DependencyInjection.Common\Alchemist.DependencyInjection.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Exceptions\Alchemist.Exceptions.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Adapter\Alchemist.Import.Settings.DataAdapter.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Category\Alchemist.Import.Settings.Category.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Extensions\Alchemist.Import.Settings.Extensions.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Product\Alchemist.Import.Settings.Product.csproj" />
    <ProjectReference Include="..\Alchemist.Messages.Common\Alchemist.Messages.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Entities\Alchemist.Product.Entities.csproj" />
    <ProjectReference Include="..\Import.Service.Infrastructure\Import.Service.Infrastructure.csproj" />
    <ProjectReference Include="..\Shop.Entities\Shop.Interfaces.csproj" />
  </ItemGroup>

</Project>
