<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>41916d12-4d8d-47f7-bb4f-83d8e5d976de</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <Configurations>Debug;Release;debug libs</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Data.Postgresql\Alchemist.Product.Data.Postgresql.csproj" />
    <ProjectReference Include="..\Alchemist.Product.DataService.Interfaces\Alchemist.DataService.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Log.Extensions\Alchemist.Log.Serilog.csproj" />
    <ProjectReference Include="..\Alchemist.Common\Alchemist.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Data.Repository\Alchemist.Product.Data.Repository.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Entities\Alchemist.Product.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Http.ErrorHandling">
      <HintPath>..\Libs\Http\ErrorHandling\Http.ErrorHandling.dll</HintPath>
    </Reference>
    <Reference Include="Http.Info">
      <HintPath>..\Libs\Http\Info\Http.Info.dll</HintPath>
    </Reference>
    <Reference Include="Http.RequestHandling.Interfaces">
      <HintPath>..\Libs\Http\RequestHandling.Interfaces\Http.RequestHandling.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Http.RequestHandling.PerfomanceCounter">
      <HintPath>..\Libs\Http\RequestHandling.PerfomanceCounter\Http.RequestHandling.PerfomanceCounter.dll</HintPath>
    </Reference>
    <Reference Include="Log.Interceptors">
      <HintPath>..\Libs\Log\Log.Interceptors\Log.Interceptors.dll</HintPath>
    </Reference>
    <Reference Include="Message.Interfaces">
      <HintPath>..\Libs\Message\Message.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR">
      <HintPath>..\Libs\Message\SignalR\Message.SignalR.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR.DependencyInjection">
      <HintPath>..\Libs\Message\SignalR.DependencyInjection\Message.SignalR.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Configuration.Extensions">
      <HintPath>..\Libs\Log\Serilog.Configuration.Extensions\Serilog.Configuration.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Loggers">
      <HintPath>..\Libs\Log\Serilog.Loggers\Serilog.Loggers.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="log.property.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
