[vcs]
provider = "GITHUB"

[vcs.github.http_client]
# Токен мы передадим через переменную окружения для безопасности
api_token = "${VCS__GITHUB__HTTP_CLIENT__API_TOKEN}"

[vcs.github.pipeline.pull_request]
id = ${VCS__GITHUB__PIPELINE__PULL_REQUEST__ID}

[llm]
provider = "OLLAMA"

[llm.ollama.http_client]
base_url = "http://docker.internal"

[llm.ollama.meta]
model = "qwen2.5-coder:1.5b"

[review.core]
language = "English"
summary_report = true
system_prompt = "You are a Senior C# Developer. Review code for bugs and logic errors."
