syntax = "proto3";

option csharp_namespace = "Alchemist.Product.GrpcService";

package alchemygrpc;

import "google/api/annotations.proto";
import "google/api/http.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

// The alchemy service definition.
service AlchemyGrpcService {
	rpc CreateProductType(CreateProductTypeRequest) returns (ProductTypeReply) {
		option (google.api.http) = {
			post: "/v1/productTypes"
			body: "*"
		};
	}
	rpc FindProductTypeByName(FindByNameRequest) returns (ProductTypeReply) {
		option (google.api.http) = {
			get: "/v1/productTypes/findByName/{name}"
		};
	}
	
	rpc CreatePurposeType(CreatePurposeTypeRequest) returns (PurposeTypeReply) {
		option (google.api.http) = {
			post: "/v1/purposeTypes"
			body: "*"
		};
	}
	rpc FindPurposeTypeByName(FindByNameRequest) returns (PurposeTypeReply) {
		option (google.api.http) = {
			get: "/v1/purposeTypes/findByName/{name}"
		};
	}

	rpc CreateCountry(CreateCountryRequest) returns (CountryReply) {
		option (google.api.http) = {
			post: "/v1/countries"
			body: "*"
		};
	}
	rpc FindCountryByName(FindByNameRequest) returns (CountryReply) {
		option (google.api.http) = {
			get: "/v1/countries/findByName/{name}"
		};
	}

	rpc CreateBrand(CreateBrandRequest) returns (BrandReply) {
		option (google.api.http) = {
			post: "/v1/brands"
			body: "*"
		};
	}
	rpc FindBrandByName(FindByNameRequest) returns (BrandReply) {
		option (google.api.http) = {
			get: "/v1/brands/findByName/{name}"
		};
	}		
	
	rpc CreateComponent(CreateComponentRequest) returns (ComponentReply) {
		option (google.api.http) = {
			post: "/v1/components"
			body: "*"
		};
	}
	rpc GetComponent(GetByIdInt32Request) returns (ComponentReply) {
		option (google.api.http) = {
			get: "/v1/components/{id}"
		};
	}	
	rpc FindComponentByName(FindByNameRequest) returns (ComponentReply) {
		option (google.api.http) = {
			get: "/v1/components/findByName/{name}"
		};
	}

	rpc CreateProduct(CreateProductRequest) returns (ProductReply) {
		option (google.api.http) = {
			post: "/v1/products"
			body: "*"
		};
	}
	rpc FindProductByName(FindByNameRequest) returns (ProductReply) {
		option (google.api.http) = {
			get: "/v1/products/findByName/{name}"
		};
	}
	rpc FindProductByNameAndBrand(FindProductByNameAndBrandRequest) returns (ProductReply) {
		option (google.api.http) = {
			get: "/v1/products/findByNameAndBrand/{name}/{brand}"
		};
	}

	rpc GetShopProductByShopAndApiUrl(GetShopProductByShopAndApiUrlRequest) returns (ShopProductReply) {
		option (google.api.http) = {
			get: "/v1/shops/{shopId}/products/byApiUrl/{apiUrl}"
		};
	}
	rpc GetShopProductByShopAndItemId(GetShopProductByShopAndItemIdRequest) returns (ShopProductReply) {
		option (google.api.http) = {
			get: "/v1/shops/{shopId}/products/byItemId/{itemId}"
		};
	}
	rpc GetShopProductByShopAndProductId(GetShopProductByShopAndProductIdRequest) returns (ShopProductReply) {
		option (google.api.http) = {
			get: "/v1/shops/{shopId}/products/{productId}"
		};
	}
	rpc UpdateShopProduct(UpdateShopProductRequest) returns(ShopProductReply) {
		option (google.api.http) = {
			put: "/v1/shops/{shopId}/products/{id}"
			body: "*"
		};
	}
	rpc CreateShopProduct(CreateShopProductRequest) returns(ShopProductReply) {
		option (google.api.http) = {
			post: "/v1/shops/{shopId}/products"
			body: "*"
		};
	}

	rpc SetProductComponent(SetProductComponentRequest) returns(ProductComponentReply) {
		option (google.api.http) = {
			post: "/v1/products/{productId}/components"
			body: "*"
		};
	}

	rpc GetProductPurposes(GetProductPurposesRequest) returns(PurposeTypeListReply) {
		option (google.api.http) = {
			get: "/v1/products/{productId}/purposes"
		};
	}
	rpc SetProductPurpose(SetProductPurposeRequest) returns(ProductPurposeReply) {
		option (google.api.http) = {
			post: "/v1/products/{productId}/purposes"
			body: "*"
		};
	}

	rpc GetCurrencyByName(FindByNameRequest) returns (CurrencyReply) {
		option (google.api.http) = {
			get: "/v1/currencies/findByName/{name}"
		};
	}
	rpc GetCurrencyByCode(GetCurrencyByCodeRequest) returns (CurrencyReply) {
		option (google.api.http) = {
			get: "/v1/currencies/{code}"
		};
	}
	rpc CreateCurrency(CreateCurrencyRequest) returns(CurrencyReply) {
		option (google.api.http) = {
			post: "/v1/currencies"
			body: "*"
		};
	}

	rpc GetShopProductPrice(GetByIdInt64Request) returns(ShopProductPriceReply) {
		option (google.api.http) = {
			get: "/v1/shopProductPrices/{id}"
		};
	}
	rpc CreateShopProductPrice(CreateShopProductPriceRequest) returns(ShopProductPriceReply) {
		option (google.api.http) = {
			post: "/v1/shopProductPrices"
			body: "*"
		};
	}
	rpc UpdateShopProductPrice(UpdateShopProductPriceRequest) returns(ShopProductPriceReply) {
		option (google.api.http) = {
			put: "/v1/shopProductPrices/{id}"
			body: "*"
		};
	}
	rpc GetShopProductCategories(GetByIdInt64Request) returns(ShopProductCategoryListReply) {
		option (google.api.http) = {
			get: "/v1/shopProducts/{id}/categories"
		};
	}
	rpc AddShopProductCategory(ShopProductCategoryRequest) returns(ShopProductCategoryReply) {
		option (google.api.http) = {
			post: "/v1/shopProducts/{shopProductId}/categories"
			body: "*"
		};
	}
	rpc CheckShopProductCategory(ShopProductCategoryRequest) returns(google.protobuf.BoolValue) {
		option (google.api.http) = {
			get: "/v1/shopProducts/{shopProductId}/categories/check/{shopCategoryid}"
		};
	}
}

message GetByIdInt32Request
{
	int32 id = 1;
}

message GetByIdInt64Request
{
	int64 id = 1;
}

message FindByNameRequest
{
	string name = 1;
}

message CreateProductTypeRequest{
  string name=1;  
}

message ProductTypeReply{
  int32 id = 1;
  string name=2;
  google.protobuf.StringValue warning = 3;
}

message CreatePurposeTypeRequest{
  string name=1;  
}

message PurposeTypeReply{
  int32 id = 1;
  string name=2;
  google.protobuf.StringValue warning = 3;
}

message CreateCountryRequest{
  string name=1;  
  google.protobuf.StringValue transcript = 2;
}

message CountryReply{
  int32 id = 1;
  string name=2;
  google.protobuf.StringValue transcript=3;
  google.protobuf.StringValue warning = 4;
}

message CreateBrandRequest{
  string name=1;
  google.protobuf.Int32Value countryid=2;
  google.protobuf.StringValue comment = 3;
}

message BrandReply{
  int32 id = 1;
  string name=2;
  google.protobuf.Int32Value countryid=3;
  google.protobuf.StringValue comment=4;
  google.protobuf.StringValue warning = 5;
}

message CreateComponentRequest{
  string name=1;
  google.protobuf.StringValue description=2;
  google.protobuf.Int32Value groupid=3;
  google.protobuf.StringValue transcript=4;
}

message ComponentReply{
  int32 id = 1;
  string name=2;
  google.protobuf.StringValue description=3;
  google.protobuf.Int32Value groupid=4;
  google.protobuf.StringValue transcript = 5;
  google.protobuf.StringValue warning = 6;
}

message CreateProductRequest{
  string name=1;
  google.protobuf.StringValue transcript=2;
  google.protobuf.Int32Value brandid=3;
  google.protobuf.StringValue articul=4;
  google.protobuf.Int32Value initshopid=5;
  int32 producttypeid=6;
}

message FindProductByNameAndBrandRequest
{
	string name=1;
	string brand=2;
}

message ProductReply{
  int64 id = 1;
  string name=2;
  google.protobuf.StringValue transcript=3;
  google.protobuf.Int32Value brandid=4;
  google.protobuf.StringValue articul=5;
  google.protobuf.Int32Value initshopid=6;
  int32 producttypeid=8;
  google.protobuf.StringValue warning = 9;
}

message CreateShopProductRequest
{
	int64 productid=1;
	int32 shopid=2;
	string itemid=3;
	string apiurl=4;
	google.protobuf.StringValue itemurl=5;
	google.protobuf.BoolValue isactual=6; 
	 google.protobuf.DoubleValue price=7;
}

message GetShopProductByShopAndApiUrlRequest
{
	int32 shopid=1;
	string apiurl=2;
}

message GetShopProductByShopAndItemIdRequest
{
	int32 shopid=1;
	string itemid=2;
}

message GetShopProductByShopAndProductIdRequest
{
	int32 shopid=1;
	int64 productid=2;
}

message UpdateShopProductRequest
{
	int64 id=1;
	int64 productid=2;
	int32 shopid=3;
	string itemid=4;
	string apiurl=5;
	google.protobuf.StringValue itemurl=6;
	google.protobuf.BoolValue isactual=7;
	google.protobuf.DoubleValue price=8;
}

message ShopProductReply
{
	int64 id=1;
	int64 productid=2;
	int32 shopid=3;
	string itemid=4;
	string apiurl=5;
	google.protobuf.StringValue itemurl=6;
	google.protobuf.BoolValue isactual=7; 
	 google.protobuf.DoubleValue price=8;
	 google.protobuf.StringValue warning = 9;
}

message SetProductComponentRequest
{
	int64 productid=1;
	int32 componentid=2;
	int32 sequalNumber=3;
}

message ProductComponentReply
{
	int64 productid=1;
	int32 componentid=2;
	int32 sequalNumber=3;
}

message SetProductPurposeRequest
{
	int64 productid=1;
	int32 purposetypeid=2;
}

message ProductPurposeReply
{
	int64 productid=1;
	int32 purposetypeid=2;
}

message GetProductPurposesRequest
{
	int64 productid=1;
}

message PurposeTypeListReply
{
	repeated PurposeTypeReply PurposeTypes = 1;
}

message GetCurrencyByCodeRequest
{
	int32 code=1;
}

message CurrencyReply
{
	int32 id=1;
	string name=2;
	google.protobuf.StringValue fullname=3;
	google.protobuf.Int32Value code=4;
	google.protobuf.StringValue warning = 5;
}

message CreateCurrencyRequest
{
	string name=1;
	google.protobuf.StringValue fullname=2;
	google.protobuf.Int32Value code=3;
}

message CreateShopProductPriceRequest
{
	int64 shopproductid=1;
	double price=2;
	int32 currencyid=3;
}

message UpdateShopProductPriceRequest
{
	int64 id=1;
	int64 shopproductid=2;
	double price=3;
	int32 currencyid=4;
}

message ShopProductPriceReply
{
	int64 id=1;
	int64 shopproductid=2;
	double price=3;
	int32 currencyid=4;
}

message ShopProductCategoryRequest
{
	int64 id=1;
	int64 shopproductid=2;
	int32 shopcategoryid=3;
}

message ShopProductCategoryReply
{
	int64 id=1;
	int64 shopproductid=2;
	int32 shopcategoryid=3;
}

message ShopProductCategoryListReply
{
	repeated ShopProductCategoryReply ShopProductCategories = 1;
}