<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="9.0.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="FaceIT.Hangfire.Tags" Version="1.9.0" />
		<PackageReference Include="FaceIT.Hangfire.Tags.Redis.StackExchange" Version="1.9.2" />
		<PackageReference Include="Import.Factory.Interfaces" Version="1.0.0.5" />
		<PackageReference Include="Import.Service" Version="1.0.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
		<PackageReference Include="Hangfire" Version="1.8.23" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />

	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import.Products.Interfaces\Alchemist.Import.Products.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Category\Alchemist.Import.Settings.Category.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Product\Alchemist.Import.Settings.Product.csproj" />
    <ProjectReference Include="..\Import.Service.Infrastructure\Import.Service.Infrastructure.csproj" />
    <ProjectReference Include="..\Mediator.Messages\Mediator.Messages.csproj" />
  </ItemGroup>

</Project>
