//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Import.Category.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportCategoryLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportCategoryLogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Import.Category.Service.ImportCategoryLogMessages", typeof(ImportCategoryLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories for shop {0} {1} was not loaded. See error log..
        /// </summary>
        internal static string CategoriesWereNotLoaded {
            get {
                return ResourceManager.GetString("CategoriesWereNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0}-{1} for shop {2} was handled..
        /// </summary>
        internal static string CategoryNameIdForShopWasHandled {
            get {
                return ResourceManager.GetString("CategoryNameIdForShopWasHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0}-{1} for shop {2} was loaded..
        /// </summary>
        internal static string CategoryNameIdForShopWasLoaded {
            get {
                return ResourceManager.GetString("CategoryNameIdForShopWasLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category from url {0} was not loaded. See error log..
        /// </summary>
        internal static string CategoryWasNotLoaded {
            get {
                return ResourceManager.GetString("CategoryWasNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children for category {0} were not loaded. See error log..
        /// </summary>
        internal static string ChildrenForCategoryWereNotLoaded {
            get {
                return ResourceManager.GetString("ChildrenForCategoryWereNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item handling error..
        /// </summary>
        internal static string ItemHandlingError {
            get {
                return ResourceManager.GetString("ItemHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on parsing {0}. {1}..
        /// </summary>
        internal static string ParseFromUrlFailed {
            get {
                return ResourceManager.GetString("ParseFromUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on parsing html {0}. {1}..
        /// </summary>
        internal static string ParseHtmlFromUrlFailed {
            get {
                return ResourceManager.GetString("ParseHtmlFromUrlFailed", resourceCulture);
            }
        }
    }
}
