//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Import.Category.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportCategoryLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportCategoryLogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Import.Category.Json.ImportCategoryLogMessages", typeof(ImportCategoryLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0}-{1} for shop {2} was handled..
        /// </summary>
        internal static string CategoryNameIdForShopWasHandled {
            get {
                return ResourceManager.GetString("CategoryNameIdForShopWasHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0}-{1} for shop {2} was loaded..
        /// </summary>
        internal static string CategoryNameIdForShopWasLoaded {
            get {
                return ResourceManager.GetString("CategoryNameIdForShopWasLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json document not loaded from url {0} with warning {1}..
        /// </summary>
        internal static string JsonDocumentNotLoadedFromUrlWithWarning {
            get {
                return ResourceManager.GetString("JsonDocumentNotLoadedFromUrlWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json document loading from url {0} failed with error {1}..
        /// </summary>
        internal static string JsonLoadFromUrlFailed {
            get {
                return ResourceManager.GetString("JsonLoadFromUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} cancelled on loading child categories.
        /// </summary>
        internal static string ServiceCancelledOnLoadingChildCategories {
            get {
                return ResourceManager.GetString("ServiceCancelledOnLoadingChildCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} cancelled on loading start categories..
        /// </summary>
        internal static string ServiceCancelledOnLoadingStartCategories {
            get {
                return ResourceManager.GetString("ServiceCancelledOnLoadingStartCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} category {1} failed on loading from url {2}. {3}..
        /// </summary>
        internal static string ServiceCategoryFailedOnLoadingFromUrl {
            get {
                return ResourceManager.GetString("ServiceCategoryFailedOnLoadingFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} not loaded categories. {1}..
        /// </summary>
        internal static string ServiceNotLoadedCategories {
            get {
                return ResourceManager.GetString("ServiceNotLoadedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} not loaded child categories. {1}..
        /// </summary>
        internal static string ServiceNotLoadedChildCategories {
            get {
                return ResourceManager.GetString("ServiceNotLoadedChildCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} not loaded json document from url {1}, operation was cancelled..
        /// </summary>
        internal static string ServiceNotLoadedJsonDocFromUrlOperationWasCancelled {
            get {
                return ResourceManager.GetString("ServiceNotLoadedJsonDocFromUrlOperationWasCancelled", resourceCulture);
            }
        }
    }
}
