<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import.Products.Service\Alchemist.Import.Products.Service.csproj" />
    <ProjectReference Include="..\ShopImport.ServiceHash\ShopImport.KeyHash.csproj" />
    <ProjectReference Include="..\ShopImport.ServiceState\ShopImport.ServiceState.csproj" />
  </ItemGroup>

</Project>
