<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Interfaces\Alchemist.Product.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Interfaces\Alchemist.Import.Settings.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DependencyInjection.Interfaces">
      <HintPath>..\Libs\DependencyInjection\DependencyInjection.Interfaces.dll</HintPath>
    </Reference>   
  </ItemGroup>

</Project>
