<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import.Category.Interfaces\Alchemist.Import.Category.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Product.CategoryData.Interfaces\Alchemist.Product.CategoryData.csproj" />
    <ProjectReference Include="..\Alchemist.Product.ImportItemHandler\Alchemist.BackgroundQueueItemHandler.csproj" />
    <ProjectReference Include="..\Shop.Entities\Shop.Interfaces.csproj" />
  </ItemGroup>

</Project>
