<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Import.Interfaces" Version="1.0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import\Alchemist.Import.csproj" />
  </ItemGroup>

</Project>
