<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.12.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Import\Import.Interfaces\Import.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Common\Alchemist.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Category.Json.Factory\Alchemist.Import.Factory.Category.csproj" />
  </ItemGroup>

</Project>
