<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import.BrowserService.Factory\Alchemist.Import.BrowserService.Factory.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Factory.Logging\Alchemist.Import.Logging.Factory.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Factory.Interfaces\Alchemist.Import.Service.Factory.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WebLoader.Interfaces" Version="1.0.0.4" />
    <PackageReference Include="Http.RequestHandling.PerfomanceCounter" Version="1.0.0.1" />
  </ItemGroup>

</Project>
