<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>efcb67c2-b5fc-41b5-a48a-387cdcdf230e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>  

  <ItemGroup>
    <Protobuf Include="Protos\alchemygrpc.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Interception.Extensions" Version="1.0.0" />
    <PackageReference Include="Grpc.Message.Extensions" Version="1.0.0" />
    <PackageReference Include="Grpc.Server.Interceptors" Version="1.0.0.1" />
    <PackageReference Include="Grpc.Server.RequestInterceptor" Version="1.0.0" />
    <PackageReference Include="Grpc.StatusProto" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Http.RequestHandling.PerfomanceCounter" Version="1.0.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Serilog.Loggers" Version="1.0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Exceptions\Alchemist.Exceptions.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Data.Postgresql\Alchemist.Product.Data.Postgresql.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Data.Repository\Alchemist.Product.Data.Repository.csproj" />
    <ProjectReference Include="..\Alchemist.Product.DataService.Interfaces\Alchemist.DataService.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Entities\Alchemist.Product.Entities.csproj" />
    <ProjectReference Include="..\Alchemist.Product.GrpcService.Extensions\Alchemist.Product.GrpcService.Extensions.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Interfaces\Alchemist.Product.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Log.Extensions\Alchemist.Log.Extensions.csproj" />
  </ItemGroup>

</Project>
