<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.CategoryData.Interfaces\Alchemist.Product.CategoryData.csproj" />
    <ProjectReference Include="..\Alchemist.Product.DbItemHandler\Alchemist.Product.DbItemHandler.csproj" />
  </ItemGroup>

</Project>
