<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Data\Alchemist.Product.Data.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Infrastructure\Alchemist.Product.Infrastructure.csproj" />
    <ProjectReference Include="..\Mediator.Infrastructure.EF\Mediator.Infrastructure.EF.csproj" />
  </ItemGroup>

</Project>
