<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alchemist.Shop.GoldenApple.ImportService.HttpClient.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release;debug libs</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BrowserDataLoader.Firefox.Standart.Windows" Version="1.0.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Http.RequestHandling.Interfaces" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Json.FileExtensions" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Shop.GoldApple.Model\Alchemist.Product.Shop.GoldApple.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WebLoader.Common">
      <HintPath>..\Libs\webLoader\WebLoader.Common.dll</HintPath>
    </Reference>   
    <Reference Include="WebLoader.Interfaces">
      <HintPath>..\Libs\webLoader\WebLoader.Interfaces.dll</HintPath>
    </Reference>    
    <Reference Include="WebLoader.Playwright">
      <HintPath>..\Libs\webLoader\Playwright\Firefox\WebLoader.Playwright.dll</HintPath>
    </Reference>
    <Reference Include="WebLoader.Playwright.Firefox">
      <HintPath>..\Libs\webLoader\Playwright\Firefox\WebLoader.Playwright.Firefox.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
