<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Alchemist.Shop.GoldenApple.ImportService.HttpClient.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="GoldApple.Headers.Firefox.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="GoldApple.Headers.Firefox.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BrowserDataLoader.Firefox.Standart.Windows" Version="1.0.0.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Http.RequestHandling.Interfaces" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Json.FileExtensions" Version="1.0.0" />
    <PackageReference Include="WebLoader.Playwright.Firefox" Version="1.0.1.3" />
    <PackageReference Include="WebLoader.Playwright.ChromiumPatchright" Version="1.0.0.1" />
    <PackageReference Include="WebLoader.HttpClient" Version="1.0.1.3" />
	<PackageReference Include="BrowserLauncher.Firefox.Windows.Standart" Version="1.0.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Shop.GoldApple.Model\Alchemist.Product.Shop.GoldApple.Model.csproj" />
    <ProjectReference Include="..\Alchemist.Test.Product.Shop\Alchemist.Test.Product.Shop.csproj" />
  </ItemGroup>  

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
