<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BrowserDataLoader.Firefox.Standart.Windows" Version="1.0.0.4" GeneratePathProperty="true" />
		<PackageReference Include="WebLoader.HttpClient" Version="1.0.1.3" />
		<PackageReference Include="WebLoader.Playwright.Firefox" Version="1.0.1.3" GeneratePathProperty="true" />
		<PackageReference Include="WebLoader.Playwright.ChromiumPatchright" Version="1.0.0.1" GeneratePathProperty="true" />
		<PackageReference Include="BrowserLauncher.Firefox.Windows.Standart" Version="1.0.0.2" GeneratePathProperty="true" />
		<PackageReference Include="BrowserLauncher.Firefox.Windows.DevEdition" Version="1.0.0.2" GeneratePathProperty="true" />
		<PackageReference Include="BrowserDataLoader.Firefox.DevEdition.Windows" Version="1.0.0.4" GeneratePathProperty="true" />
	</ItemGroup>

	<Target Name="RemoveBrowserDataLoaderDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserDataLoader" />
	</Target>

	<Target Name="RemoveBrowserDataLoaderFirefoxDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserDataLoader\Firefox\Standart" />
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserDataLoader\Firefox\DevEdition" />
	</Target>	
	
	<Target Name="CopyBrowserDataLoaderFirefox" AfterTargets="Build">
		<ItemGroup>
			<BrowserDataLoaderFirefoxFiles Include="$(PkgBrowserDataLoader_Firefox_Standart_Windows)\lib\dependencies\*.dll"></BrowserDataLoaderFirefoxFiles>
			<CopyBrowserDataLoaderNativeFiles Include="$(PkgBrowserDataLoader_Firefox_Standart_Windows)\lib\dependencies\**\*.*"></CopyBrowserDataLoaderNativeFiles>
			<BrowserDataLoaderFirefoxDevEditionFiles Include="$(PkgBrowserDataLoader_Firefox_DevEdition_Windows)\lib\dependencies\*.dll"></BrowserDataLoaderFirefoxDevEditionFiles>
			<CopyBrowserFirefoxDevEditionNativeFiles Include="$(PkgBrowserDataLoader_Firefox_DevEdition_Windows)\lib\dependencies\**\*.*"></CopyBrowserFirefoxDevEditionNativeFiles>
		</ItemGroup>
		<Copy SourceFiles="@(BrowserDataLoaderFirefoxFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserDataLoader\Firefox\Standart"></Copy>
		<Copy SourceFiles="@(BrowserDataLoaderFirefoxDevEditionFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserDataLoader\Firefox\DevEdition"></Copy>
		<Copy SourceFiles="@(CopyBrowserDataLoaderNativeFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserDataLoader\Firefox\Standart\%(RecursiveDir)"></Copy>
		<Copy SourceFiles="@(CopyBrowserFirefoxDevEditionNativeFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserDataLoader\Firefox\DevEdition\%(RecursiveDir)"></Copy>
	</Target>

	<Target Name="RemoveBrowserLauncherDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserLauncher" />
	</Target>

	<Target Name="RemoveBrowserLauncherFirefoxDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserLauncher\Firefox\Standart" />
		<RemoveDir Directories="$(SolutionDir)Libs\BrowserLauncher\Firefox\DevEdition" />
	</Target>

	<Target Name="CopyBrowserLauncherFirefox" AfterTargets="Build">
		<ItemGroup>
			<BrowserLauncherFirefoxStandartFiles Include="$(PkgBrowserLauncher_Firefox_Windows_Standart)\lib\dependencies\*.dll"></BrowserLauncherFirefoxStandartFiles>
			<BrowserLauncherFirefoxDevEditionFiles Include="$(PkgBrowserLauncher_Firefox_Windows_DevEdition)\lib\dependencies\*.dll"></BrowserLauncherFirefoxDevEditionFiles>
		</ItemGroup>
		<Copy SourceFiles="@(BrowserLauncherFirefoxStandartFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserLauncher\Firefox\Standart"></Copy>
		<Copy SourceFiles="@(BrowserLauncherFirefoxDevEditionFiles)" DestinationFolder="$(SolutionDir)Libs\BrowserLauncher\Firefox\DevEdition"></Copy>
	</Target>

	<Target Name="RemoveWebLoaderDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\WebLoader" />
	</Target>

	<Target Name="RemoveWebLoaderHttpClientDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\WebLoader\HttpClient" />
	</Target>	

	<Target Name="RemoveWebLoaderPlaywrightFirefoxDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\WebLoader\Playwright\Firefox" />
	</Target>
	
	<Target Name="RemoveWebLoaderChromiumPatchrightDir" BeforeTargets="Build">
		<RemoveDir Directories="$(SolutionDir)Libs\WebLoader\Playwright\ChromiumPatchright" />
	</Target>

	<Target Name="CopyWebLoaderPlaywrightFirefox" AfterTargets="Build">
		<ItemGroup>
			<CopyWebLoaderPlaywrightFirefoxFiles Include="$(PkgWebLoader_Playwright_Firefox)\dependencies\*.dll"></CopyWebLoaderPlaywrightFirefoxFiles>
			<CopyFirefoxPlaywrightFiles Include="$(PkgWebLoader_Playwright_Firefox)\dependencies\.playwright\**\*.*"></CopyFirefoxPlaywrightFiles>
			<CopyFirefoxPlaywrightNodeFiles Include="$(PkgWebLoader_Playwright_Firefox)\dependencies\node\**\*.*"></CopyFirefoxPlaywrightNodeFiles>
			<CopyFirefoxPlaywrightPackageFiles Include="$(PkgWebLoader_Playwright_Firefox)\dependencies\package\**\*.*"></CopyFirefoxPlaywrightPackageFiles>
		</ItemGroup>
		<Copy SourceFiles="@(CopyWebLoaderPlaywrightFirefoxFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\Firefox"></Copy>
		<Copy SourceFiles="@(CopyFirefoxPlaywrightFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\Firefox\.playwright\%(RecursiveDir)"></Copy>
		<Copy SourceFiles="@(CopyFirefoxPlaywrightNodeFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\Firefox\.playwright\node\%(RecursiveDir)"></Copy>
		<Copy SourceFiles="@(CopyFirefoxPlaywrightPackageFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\Firefox\.playwright\package\%(RecursiveDir)"></Copy>
	</Target>
	
	<Target Name="CopyWebLoaderChromiumPatchright" AfterTargets="Build">
		<ItemGroup>
			<CopyWebLoaderChromiumPatchrightFiles Include="$(PkgWebLoader_Playwright_ChromiumPatchright)\dependencies\*.dll"></CopyWebLoaderChromiumPatchrightFiles>
			<CopyChromiumPatchrightFiles Include="$(PkgWebLoader_Playwright_ChromiumPatchright)\dependencies\.playwright\**\*.*"></CopyChromiumPatchrightFiles>
			<CopyChromiumPatchrightNodeFiles Include="$(PkgWebLoader_Playwright_ChromiumPatchright)\dependencies\node\**\*.*"></CopyChromiumPatchrightNodeFiles>
			<CopyChromiumPatchrightPackageFiles Include="$(PkgWebLoader_Playwright_ChromiumPatchright)\dependencies\package\**\*.*"></CopyChromiumPatchrightPackageFiles>
		</ItemGroup>
		<Copy SourceFiles="@(CopyWebLoaderChromiumPatchrightFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\ChromiumPatchright"></Copy>
		<Copy SourceFiles="@(CopyChromiumPatchrightFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\ChromiumPatchright\.playwright\%(RecursiveDir)"></Copy>
		<Copy SourceFiles="@(CopyChromiumPatchrightNodeFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\ChromiumPatchright\.playwright\node\%(RecursiveDir)"></Copy>
		<Copy SourceFiles="@(CopyChromiumPatchrightPackageFiles)" DestinationFolder="$(SolutionDir)Libs\WebLoader\Playwright\ChromiumPatchright\.playwright\package\%(RecursiveDir)"></Copy>
	</Target>

</Project>
