//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Import.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Import.Service.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response status code {0} for url {1}. Web loader {2} will be restarted..
        /// </summary>
        internal static string HttpRequestErrorAndWebLoaderRestart {
            get {
                return ResourceManager.GetString("HttpRequestErrorAndWebLoaderRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebLoader {0} was not executed. Import was stopped..
        /// </summary>
        internal static string ImportWasStoppedWebLoaderNotExecute {
            get {
                return ResourceManager.GetString("ImportWasStoppedWebLoaderNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process url {0} failed.
        /// </summary>
        internal static string ProcessUrlFailedError {
            get {
                return ResourceManager.GetString("ProcessUrlFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process url {0} not complete. Warning : {1}..
        /// </summary>
        internal static string ProcessUrlNotCompleteWarning {
            get {
                return ResourceManager.GetString("ProcessUrlNotCompleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request url {0} failed with error {1} and status code {2}.
        /// </summary>
        internal static string RequestUrlFailedWithErrorAndStatusCode {
            get {
                return ResourceManager.GetString("RequestUrlFailedWithErrorAndStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many request. Thread would be sleeped 10 sec..
        /// </summary>
        internal static string TooManyRequestsError {
            get {
                return ResourceManager.GetString("TooManyRequestsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web loader is reseting....
        /// </summary>
        internal static string WebLoaderIsReseting {
            get {
                return ResourceManager.GetString("WebLoaderIsReseting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer {0} not started.Warning : {1}..
        /// </summary>
        internal static string WebLoaderNotStartedWarning {
            get {
                return ResourceManager.GetString("WebLoaderNotStartedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web loader reset successfully..
        /// </summary>
        internal static string WebLoaderResetSuccessfully {
            get {
                return ResourceManager.GetString("WebLoaderResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web loader throws redirect loop exception and will be reseted. {0}.
        /// </summary>
        internal static string WebLoaderThrowsNsRedirectLoopAndWillBeReseted {
            get {
                return ResourceManager.GetString("WebLoaderThrowsNsRedirectLoopAndWillBeReseted", resourceCulture);
            }
        }
    }
}
