<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Import.Factory.Interfaces" Version="1.0.0.2" />
    <PackageReference Include="Import.Interfaces" Version="1.0.0.1" />
	<PackageReference Include="MediatR" Version="14.0.0" />
	<PackageReference Include="Message.Interfaces" Version="1.0.0.3" />
	<PackageReference Include="Autofac" Version="9.0.0" />
	<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.BackgroundTaskQueue\BackgroundTaskQueue.csproj" />
    <ProjectReference Include="..\Alchemist.DependencyInjection.Common\Alchemist.DependencyInjection.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Adapter\Alchemist.Import.Settings.DataAdapter.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Category\Alchemist.Import.Settings.Category.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Extensions\Alchemist.Import.Settings.Extensions.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Product\Alchemist.Import.Settings.Product.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings\Alchemist.Import.Settings.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Entities\Alchemist.Product.Entities.csproj" />
    <ProjectReference Include="..\Mediator.Messages\Mediator.Messages.csproj" />
    <ProjectReference Include="..\Shop.Entities\Shop.Interfaces.csproj" />
    <ProjectReference Include="..\ShopSettings.Interfaces\ShopSettings.Interfaces.csproj" />
  </ItemGroup>

</Project>
