<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;debug libs</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BrandRepository.cs" />
    <Compile Remove="ComponentGroupRepository.cs" />
    <Compile Remove="ComponentRepository.cs" />
    <Compile Remove="CountryRepository.cs" />
    <Compile Remove="IRepository.cs" />
    <Compile Remove="ProductComponentRepository.cs" />
    <Compile Remove="ProductRepository.cs" />
    <Compile Remove="ProductTypeRepository.cs" />
    <Compile Remove="PurposeComponentGroupRepository.cs" />
    <Compile Remove="PurposeTypeRepository.cs" />
    <Compile Remove="RepositoryBase.cs" />
    <Compile Remove="ShopProductRepository.cs" />
    <Compile Remove="ShopRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Common\Alchemist.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Exceptions\Alchemist.Exceptions.csproj" />
    <ProjectReference Include="..\Alchemist.Product.DataService.Interfaces\Alchemist.DataService.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Data\Alchemist.Product.Data.csproj" />
  </ItemGroup>

</Project>
