//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Import.Products.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportProductLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportProductLogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Import.Products.Service.ImportProductLogMessages", typeof(ImportProductLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} completed. {1} products handled. {2} unhandled..
        /// </summary>
        internal static string CategoryCompletedInfo {
            get {
                return ResourceManager.GetString("CategoryCompletedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} load with fatal error {1}..
        /// </summary>
        internal static string CategoryProcessFault {
            get {
                return ResourceManager.GetString("CategoryProcessFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} was loaded with not fatal error {1}..
        /// </summary>
        internal static string CategoryProcessWarning {
            get {
                return ResourceManager.GetString("CategoryProcessWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} recompleted succsessfully. {1} product items handled..
        /// </summary>
        internal static string CategoryRecompletedInfo {
            get {
                return ResourceManager.GetString("CategoryRecompletedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} was not recompleted. Error {1}..
        /// </summary>
        internal static string CategoryRecompletedWarning {
            get {
                return ResourceManager.GetString("CategoryRecompletedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} rehandling was failed. Error {1}..
        /// </summary>
        internal static string CategoryRehandlingFailed {
            get {
                return ResourceManager.GetString("CategoryRehandlingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category {0} is enqueued..
        /// </summary>
        internal static string NewCategoryIsEnqueued {
            get {
                return ResourceManager.GetString("NewCategoryIsEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} from url {1} handled with status {2}..
        /// </summary>
        internal static string ProductFromUrlHandledWithStatusInfo {
            get {
                return ResourceManager.GetString("ProductFromUrlHandledWithStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product item from {0} is null..
        /// </summary>
        internal static string ProductFromUrlIsNullError {
            get {
                return ResourceManager.GetString("ProductFromUrlIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} has been successfully loaded from url {1}..
        /// </summary>
        internal static string ProductHasBeenSuccessfullyLoadedFromUrl {
            get {
                return ResourceManager.GetString("ProductHasBeenSuccessfullyLoadedFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} was not loaded from url {1} with not fatal error {2} and would be reload..
        /// </summary>
        internal static string ProductWasNotLoadedFromUrlWithWarningAndWouldBeReloaded {
            get {
                return ResourceManager.GetString("ProductWasNotLoadedFromUrlWithWarningAndWouldBeReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} was stopped..
        /// </summary>
        internal static string ServiceWasStopped {
            get {
                return ResourceManager.GetString("ServiceWasStopped", resourceCulture);
            }
        }
    }
}
