//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemist.Import.Products.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportProductLogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportProductLogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemist.Import.Products.Service.ImportProductLogMessages", typeof(ImportProductLogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {CategoryPath} completed. {HandledProductCount} products handled. {UnhandledProductCount} unhandled..
        /// </summary>
        internal static string CategoryCompletedInfo {
            get {
                return ResourceManager.GetString("CategoryCompletedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not loaded from path {Path}. See error log..
        /// </summary>
        internal static string CategoryNotLoadedFromUrl {
            get {
                return ResourceManager.GetString("CategoryNotLoadedFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {Category} page {Page} loaded successfully..
        /// </summary>
        internal static string CategoryPageLoadedSuccessfully {
            get {
                return ResourceManager.GetString("CategoryPageLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Path {CategoryPath} were processed successfull : {ProductCount} products were loaded.
        /// </summary>
        internal static string CategoryProductsForUrlWereProcessedSuccesfullInfo {
            get {
                return ResourceManager.GetString("CategoryProductsForUrlWereProcessedSuccesfullInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products in category path {CategoryPath} were not loaded..
        /// </summary>
        internal static string CategoryProductsWereNotLoadedError {
            get {
                return ResourceManager.GetString("CategoryProductsWereNotLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load category {CategoryPath} page {Page}. See error log..
        /// </summary>
        internal static string FailedToLoadCategoryPage {
            get {
                return ResourceManager.GetString("FailedToLoadCategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load category {CategoryPath} page {Page} after {MaxAttempts} attempts..
        /// </summary>
        internal static string FailedToLoadCategoryPageAfterAttempts {
            get {
                return ResourceManager.GetString("FailedToLoadCategoryPageAfterAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load product {ProductPath} of category {Category}. See error log..
        /// </summary>
        internal static string FailedToLoadProductOfCategory {
            get {
                return ResourceManager.GetString("FailedToLoadProductOfCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category {Category} is enqueued..
        /// </summary>
        internal static string NewCategoryIsEnqueued {
            get {
                return ResourceManager.GetString("NewCategoryIsEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category from path {Category} was processed: {HandledProductsCount} products from {CategoryPath} were loaded. .
        /// </summary>
        internal static string NotAllCategoryProductsForUrlWereProcessedWarning {
            get {
                return ResourceManager.GetString("NotAllCategoryProductsForUrlWereProcessedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {ProductName} from path {ProductPath} handled with status {Status}..
        /// </summary>
        internal static string ProductFromUrlHandledWithStatusInfo {
            get {
                return ResourceManager.GetString("ProductFromUrlHandledWithStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product from path {ProductPath} handling failed..
        /// </summary>
        internal static string ProductFromUrlHandlingFailed {
            get {
                return ResourceManager.GetString("ProductFromUrlHandlingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {ProductName} has been successfully loaded from path {ProductPath}..
        /// </summary>
        internal static string ProductHasBeenSuccessfullyLoadedFromUrl {
            get {
                return ResourceManager.GetString("ProductHasBeenSuccessfullyLoadedFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product was not loaded from path {ProductPath} ..
        /// </summary>
        internal static string ProductWasNotLoadedFromUrlWithError {
            get {
                return ResourceManager.GetString("ProductWasNotLoadedFromUrlWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {Item} from path {ItemPath} was not deserialized..
        /// </summary>
        internal static string SerializationFailed {
            get {
                return ResourceManager.GetString("SerializationFailed", resourceCulture);
            }
        }
    }
}
