<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>   
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
	<PackageReference Include="Serilog.ContextFileSink" Version="1.0.0.1" />
	<PackageReference Include="CustomJsonConfigurationProvider" Version="1.0.0.1" />
  </ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\lib\alchemist_common\" />
	</ItemGroup>

	<ItemGroup>	 
	  <!-- <ProjectReference Include="..\Alchemist.Css.Common\Alchemist.Css.Common.esproj" /> -->
	  <ProjectReference Include="..\Alchemist.DependencyInjection.Common\Alchemist.DependencyInjection.Common.csproj" />
	  <ProjectReference Include="..\Alchemist.Import.Settings.Adapter\Alchemist.Import.Settings.DataAdapter.csproj" />
	  <ProjectReference Include="..\Alchemist.Import.Settings.Category\Alchemist.Import.Settings.Category.csproj" />
	  <ProjectReference Include="..\Alchemist.Import.Settings.Extensions\Alchemist.Import.Settings.Extensions.csproj" />
	  <ProjectReference Include="..\Alchemist.Import.Settings.Product\Alchemist.Import.Settings.Product.csproj" />
	  <!-- <ProjectReference Include="..\Alchemist.Js.Common\Alchemist.Js.Common.esproj" /> -->
	  <ProjectReference Include="..\Alchemist.Settings.RestAPIClient\Alchemist.Settings.RestAPIClient.csproj" />
	  <ProjectReference Include="..\Alchemist.Log.Extensions\Alchemist.Log.Extensions.csproj" />
	  <ProjectReference Include="..\Alchemist.Web.Components\Alchemist.Web.Components.csproj" />
	  <ProjectReference Include="..\Alchemist.WebApp.Api.Common\Alchemist.WebApp.Api.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="wwwroot\js\importsettings.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\js\productsettings.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\js\servicesettings.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\js\shopsettingssite.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	
	<Target Name="NpmLinkLibPackageToSolution" BeforeTargets="Build" Condition="'$(SkipNpmTargets)' != 'true'">
		<Exec Command="npm link alchemist_common alchemist_css_common" WorkingDirectory="$(SolutionDir)" />
	</Target>

	<Target Name="CopyNpmCssToWwwRoot" BeforeTargets="Build" Condition="'$(SkipNpmTargets)' != 'true'">
		<ItemGroup>
			<NpmCssFiles Include="..\node_modules\alchemist_css_common\src\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(NpmCssFiles)" DestinationFolder="wwwroot/css/common/%(RecursiveDir)" />
	</Target>

	<Target Name="CopyNpmLibsToWwwRoot" BeforeTargets="Build" Condition="'$(SkipNpmTargets)' != 'true'">
		<ItemGroup>
			<NpmLibFiles Include="..\node_modules\alchemist_common\mvc\*.*" />
			<JQueryConfirmLibFiles Include="..\node_modules\jquery-confirm\dist\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(NpmLibFiles)" DestinationFolder="wwwroot/lib/alchemist_common/%(RecursiveDir)" />
		<Copy SourceFiles="@(JQueryConfirmLibFiles)" DestinationFolder="wwwroot/lib/jquery-confirm/dist/%(RecursiveDir)" />
	</Target>

	<Target Name="NpmLinkPackage" AfterTargets="Build" Condition="'$(SkipNpmTargets)' != 'true'">
		<Exec Command="npm link" WorkingDirectory="$(SolutionDir)" />
	</Target>

</Project>
