<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>    
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Import.Category.Json\Alchemist.Import.Category.Service.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Category\Alchemist.Import.Settings.Category.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Extensions\Alchemist.Import.Settings.Extensions.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Import.Factory.Service" Version="1.0.0.1" />
	</ItemGroup>


	</Project>
