<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject> 
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Http.ErrorHandling">
      <HintPath>..\Libs\Http\ErrorHandling\Http.ErrorHandling.dll</HintPath>
    </Reference>
    <Reference Include="Http.Info">
      <HintPath>..\Libs\Http\Info\Http.Info.dll</HintPath>
    </Reference>
    <Reference Include="Http.RequestHandling.Interfaces">
      <HintPath>..\Libs\Http\RequestHandling.Interfaces\Http.RequestHandling.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Http.RequestHandling.PerfomanceCounter">
      <HintPath>..\Libs\Http\RequestHandling.PerfomanceCounter\Http.RequestHandling.PerfomanceCounter.dll</HintPath>
    </Reference>
    <Reference Include="Log.Interceptors">
      <HintPath>..\Libs\Log\Log.Interceptors\Log.Interceptors.dll</HintPath>
    </Reference>
    <Reference Include="Message.Interfaces">
      <HintPath>..\Libs\Message\Message.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR">
      <HintPath>..\Libs\Message\SignalR\Message.SignalR.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR.DependencyInjection">
      <HintPath>..\Libs\Message\SignalR.DependencyInjection\Message.SignalR.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Configuration.Extensions">
      <HintPath>..\Libs\Log\Serilog.Configuration.Extensions\Serilog.Configuration.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Loggers">
      <HintPath>..\Libs\Log\Serilog.Loggers\Serilog.Loggers.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alchemist.Product.Data\Alchemist.Product.Data.csproj" />
    <ProjectReference Include="..\Alchemist.Product.RestAPI\Alchemist.Product.RestAPI.csproj" />
    <ProjectReference Include="..\Alchemist.Test.Server.Fixtures\Alchemist.Test.Server.Fixtures.csproj" />
    <ProjectReference Include="..\Alchemist.Test.SignalRWebAppFactory\Alchemist.Test.SignalRWebAppFactory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
