<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Ozon.Headers.Firefox.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	<PackageReference Include="WebLoader.Playwright.ChromiumPatchright" Version="1.0.0.3" GeneratePathProperty="true" />
	<PackageReference Include="BrowserLauncher.Firefox.Windows.Standart" Version="1.0.0.2" />
	<PackageReference Include="WebLoader.Playwright.Firefox" Version="1.0.1.5" />
	<PackageReference Include="BrowserDataLoader.Firefox.Standart.Windows" Version="1.0.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Product.Import.Test\Product.Import.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
