<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DependencyInjection.Interfaces">
      <HintPath>..\Libs\DependencyInjection\DependencyInjection.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="WebLoader.Common">
      <HintPath>..\Libs\webLoader\WebLoader.Common.dll</HintPath>
    </Reference>
    <Reference Include="Message.Interfaces">
      <HintPath>..\Libs\Message\Message.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR">
      <HintPath>..\Libs\Message\SignalR\Message.SignalR.dll</HintPath>
    </Reference>
    <Reference Include="Message.SignalR.DependencyInjection">
      <HintPath>..\Libs\Message\SignalR.DependencyInjection\Message.SignalR.DependencyInjection.dll</HintPath>
    </Reference>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Alchemist.DependencyInjection.Common\Alchemist.DependencyInjection.Common.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Products.Interfaces\Alchemist.Import.Products.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Settings.Interfaces\Alchemist.Import.Settings.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Product.Import.ViewModel\Alchemist.Product.Import.Model.csproj" />
    <ProjectReference Include="..\Alchemist.Product.RestAPIClient\Alchemist.Product.RestAPIClient.csproj" />
    <ProjectReference Include="..\Alchemist.Settings.RestAPIClient\Alchemist.Settings.RestAPIClient.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="wwwroot\js\fileUpload.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\settings.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\js\site.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
