<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="GoldApple.Headers.Firefox.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ozon.Headers.Firefox.Standart.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ozon.CategoryLoadFullOptions.Firefox.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ozon.CategoryLoadNonHeaderOptions.Firefox.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Ozon.Headers.Firefox.Devedition.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BrowserDataLoader.Firefox.Standart.Windows" Version="1.0.0.4" />
    <PackageReference Include="BrowserDataLoader.Firefox.DevEdition.Windows" Version="1.0.0.4" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Http.RequestHandling.Interfaces" Version="1.0.0" />
    <PackageReference Include="Json.FileExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="WebLoader.Playwright.Firefox" Version="1.0.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Import\Import.Html.Factory\Import.Html.Factory.csproj" />
    <ProjectReference Include="..\..\Import\Import.Html\Import.Html.csproj" />
    <ProjectReference Include="..\..\Import\Import.Interfaces\Import.Interfaces.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Category.Service.Json\Alchemist.Import.Category.Service.Json.csproj" />
    <ProjectReference Include="..\Alchemist.Import.Category.Test\Alchemist.Import.Category.Test.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PlaywrightPlatform>all</PlaywrightPlatform>
  </PropertyGroup>
  
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="OzonCategoriesLoadTest.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
