name: 🤖 AI Review

on:
  workflow_dispatch:
    inputs:
      review-command:
        type: choice
        default: "run"
        options: [ run, run-inline, run-context, run-summary ]
        required: true
        description: "AI Review command"

      pull-request-number:
        type: string
        required: true
        description: "Pull request number"

jobs:
  ai-review:
    name: Run AI Review
    runs-on: ubuntu-latest

    services:
      ollama:
        image: ollama/ollama:latest
        ports: [ 11434:11434 ]

    steps:
      - name: 🔍 Check Ollama Logs
        run: |
          docker ps -a
          docker logs ollama   

      - name: Verify Ollama
        run: |
          sleep 5
          curl -v http://127.0.0    

      - name: Network Debug
        run: |
          docker ps
          sudo ss -tulpn | grep 11434
          # Пробуем достучаться напрямую до IP контейнера, если localhost подведет
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ollama)
          echo "Container IP: $CONTAINER_IP"
          curl -I http://$CONTAINER_IP:11434/api/tags || echo "Direct IP failed"     

      - name: ⏳ Wait for Ollama
        run: |
          for i in {1..15}; do
            # Пробуем и 127.0.0.1 и localhost
            if curl -s -m 5 http://127.0.0; then
              echo "✅ Ollama is up!"
              exit 0
            fi
            echo "⏳ Waiting... ($i/15)"
            sleep 3
          done
          echo "❌ Failed to connect"
          docker logs ollama
          exit 1
  

      - name: 📦 Pull model
        run: |
          echo "📥 Downloading model 'mistral'..."
          curl -X POST http://127.0.0.1:11434/api/pull \
            -H "Content-Type: application/json" \
            -d '{"model": "mistral"}'

      - name: 🔥 Warm up model
        run: |
          echo "🔥 Warming up model..."
          curl -s -X POST http://127.0.0.1:11434/api/chat \
            -H "Content-Type: application/json" \
            -d '{"model":"mistral","stream":false,"messages":[{"role":"user","content":"Hello!"}]}'
          echo "✅ Warm-up complete."

      - name: 🚀 Run AI Review
        uses: Nikita-Filonov/ai-review@v0.27.0
        env:
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ inputs.pull-request-number }}

        with:
          review-command: ${{ inputs.review-command }}
